# name: 'tag'
# on:
#   push:
#     branches:
#       - main
# jobs:
#   tag:
#     runs-on: ubuntu-latest
#     # run: | 
#     #   t=$(git describe --tags `git rev-list --tags --max-count=1`)
#     #   echo $t
#     steps:
#     - uses: actions/checkout@v2
#     - uses: christophebedard/tag-version-commit@v1
#       id: tag-version-commit
#       with:
#         token: ${{ secrets.TOKEN1 }}
#         version_regex: '([0-9]+\.[0-9]+\.[0-9]+)'
#         version_tag_prefix: 'V'
#         check_entire_commit_message: true
#     - run: echo "${{ steps.tag-version-commit.outputs.tag }}"
 
