name: 'tag'
on:
  push:
    branches:
      - main
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: christophebedard/tag-version-commit@v1
      with:
        token: ${{ secrets.TOKEN1 }}
        version_regex: '([0-9]+\.[0-9]+\.[0-9]+)'
        version_tag_prefix: 'V'
        check_entire_commit_message: true
    run: | 
      t=$(git describe --tags `git rev-list --tags --max-count=1`)
      echo $t
    env:
      RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
